---
- name: git pre | check to see if SSL cert already applied
  become: false
  delegate_to: localhost
  run_once: true
  failed_when: false
  register: check_cert
  community.crypto.get_certificate:
    host: "gitlab.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}"
    port: 443

- block:
    - name: git pre | Install required RPM GPG keys
      become: true
      ansible.builtin.rpm_key:
        state: present
        key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8

    - name: git pre | Install EPEL
      ansible.builtin.package:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm"
        state: present

        # temporary fix for rhel 8.2 dnf substitution

    - name: git pre | fix EPEL repo substitution
      loop:
      - /etc/yum.repos.d/epel-modular.repo
      - /etc/yum.repos.d/epel.repo
      when:
      - ansible_distribution_major_version|int == 8
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: '\$releasever'
        replace: '8'

    - name: git pre | Install base packages
      ansible.builtin.package:
        name:
        - python3-pip
        - python3-devel
        - certbot
        state: present

    - name: git pre | get some certs
      block:
        - name: git pre | issue cert
          register: issue_gitlab_cert
          until: issue_gitlab_cert is not failed
          retries: 5

                # this is used because gitea runs as non-root and needs access to the certs
                # TODO: fix add conditional for gitea or gitlab
          ansible.builtin.shell: certbot certonly --no-bootstrap --standalone -d gitlab.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}} --email ansible-network@redhat.com --noninteractive --agree-tos

        - name: git pre | set permissions on cert
          become: true
          ansible.builtin.shell: chmod -R 0755 /etc/letsencrypt/{live,archive}

        - name: git pre | use self signed cert
          set_fact:
            gitlab_create_self_signed_cert: false
            gitlab_ssl_certificate: "/etc/letsencrypt/live/gitlab.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}/fullchain.pem"
            gitlab_ssl_certificate_key: "/etc/letsencrypt/live/gitlab.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}/privkey.pem"
      rescue:
        - name: git pre | use self signed cert
          set_fact:
            gitlab_create_self_signed_cert: true

  when: check_cert.cert is not defined
