---
- name: grab facts for hub host
  amazon.aws.ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      tag:Workshop_automation-hub: "{{ec2_name_prefix}}-automation-hub"
  register: automation_hub_host_facts

- name: Add automation hub instance to host group
  when: workshop_type != "configascode"
  ansible.builtin.add_host:
    hostname: automation-hub-host
    short_name: "{{ item.tags.short_name }}"
    username: "{{ item.tags.username }}"
    ansible_user: "{{ item.tags.username }}"
    ansible_ssh_private_key_file: "{{ _ansible_ssh_private_key_file_ }}"
    ansible_host: "{{ item.public_ip_address }}"
    private_ip: "{{ item.private_ip_address }}"
    groups: "{{ automation_hub_host_facts.instances }}"
