---
- name: install git packages
  ansible.builtin.package:
    name:
      - git
    state: present

- name: Check for workshop .git/config file
  register: gitstat
  ansible.builtin.stat:
    path: "{{ _path_ }}"

- name: print output for gitstat
  ansible.builtin.debug:
    msg: "{{gitstat}}"

- name: Configure workshop repository
  check_mode: true
  register: gitrepo
  failed_when: false
  ansible.builtin.lineinfile:
    name: "{{ _name_ }}"
    line: "{{ _line_ }}"
    state: present

- block:
    - name: Set git to cache credentials
      become_user: "{{ username }}"
      ansible.builtin.command: git config --global credential.helper manager

    - name: Allow insecure git repos for self signed certificates
      become_user: "{{ username }}"
      ansible.builtin.command: git config --global http.sslVerify "false"

    - name: Set git user
      become_user: "{{ username }}"
      register: git_user
      ansible.builtin.command: git config --global user.name "{{ username }}"

    - name: Set git user email
      become_user: "{{ username }}"
      ansible.builtin.command: git config --global user.email "{{ username }}@{{ workshop_dns_zone }}"

    - name: Create project directory
      ansible.builtin.file:
        path: "{{ _path_ }}"
        state: directory
        owner: "{{ _owner_ }}"
        group: "{{ _group_ }}"

    - name: Initialize git repo
      args:
        chdir: /home/{{ username }}/windows-workshop/workshop_project
      become_user: "{{ username }}"
      ansible.builtin.command: git init

    - name: Add Git remote
      args:
        chdir: /home/{{ username }}/windows-workshop/workshop_project
      become_user: "{{ username }}"

      # - name: Create test file
      #   file:
      #     path: /home/{{ username }}/windows-workshop/workshop_project/test2
      #     state: touch
      #     owner: "{{ username }}"
      #     group: "{{ username }}"
      ansible.builtin.command: git remote add origin https://{{ student }}:{{admin_password|urlencode()}}@gitlab.{{ec2_name_prefix}}.{{workshop_dns_zone}}/{{ student
        }}/workshop_project.git

    - name: Create test file
      ansible.builtin.template:
        src: templates/README.md.j2
        dest: "{{ _dest_ }}"
        owner: "{{ _owner_ }}"
        group: "{{ _group_ }}"

    - name: Add file to git
      args:
        chdir: /home/{{ username }}/windows-workshop/workshop_project
      become_user: "{{ username }}"
      ansible.builtin.command: git add .

    - name: Commit file
      args:
        chdir: /home/{{ username }}/windows-workshop/workshop_project
      become_user: "{{ username }}"
      ansible.builtin.command: git commit -m "Initial commit"

    - name: Commit file
      command: git push origin master
      args:
        chdir: /home/{{ username }}/windows-workshop/workshop_project
      become_user: "{{ username }}"

  when: (gitrepo is changed) or (gitstat.stat.exists is not defined) or (not gitstat.stat.exists)
