---
- name: Print out pre_build var and dns_type
  ansible.builtin.debug:
    msg:
      - pre_build: "{{ pre_build | default('none set') }}"
      - dns_type: "{{ dns_type | default('none set') }}"

- name: Setup SSL for the code-server container
  when:
    - dns_type is defined
    - dns_type != "none"
  ansible.builtin.include_tasks: dns.yml

- name: setup vscode for web browser access
  ansible.builtin.include_tasks: codeserver.yml
