---
- name: Create User Group
  ansible.builtin.group:
    name: "{{ _name_ }}"
    state: present
  tags:
    - user_accounts
    - users

- name: Create User Account
  ansible.builtin.user:
    createhome: true
    group: "{{ _group_ }}"
    name: "{{ _name_ }}"
    shell: /bin/bash
    state: present
    password: "{{ admin_password_hash }}"
  tags:
    - user_accounts
    - users
