---
- name: grab boto version
  register: py_cmd
  ansible.builtin.command: "{{ansible_python['executable']}} -c 'import boto3; print(boto3.__version__)'"

- name: make sure we are running correct boto version
  ansible.builtin.assert:
    that:
    - py_cmd.stdout is version('1.7', operator='ge')
    msg: "boto3 >= 1.7 is required."

- name: check route53 information
  when: dns_type == "aws"
  block:
    - name: check for underscores in workshop name
      when:
      - "'_' in ec2_name_prefix"
      ansible.builtin.fail:
        msg: "Amazon AWS does not allow underscores _ for s3 websites, please see https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html"

    - name: does route53 zone exist
      check_mode: true
      register: test
      amazon.aws.route53_zone:
        zone: "{{ _zone_ }}"
        state: "present"

    - name: make sure workshop_dns_zone is owned by your account
      ansible.builtin.assert:
        that:
        - test.zone_id is not none
        msg: "{{ _msg_ }}"

- name: Find available AZ for region {{ ec2_region }}
  amazon.aws.aws_az_info:
    region: "{{ _region_ }}"
  register: az_names
  until: az_names is not failed

- name: Remove any AZs in the aws_az_deny_list when defined
  vars:
    __filter_query: '[?!contains(`{{ (aws_az_deny_list | default([])) | to_json }}`, zone_name)]'
  ansible.builtin.set_fact:
    availability_zones: "{{ az_names.availability_zones | json_query(__filter_query) }}"

- name: Output AWS Availability Zones (AZs)
  ansible.builtin.debug:
    var: "availability_zones"
    verbosity: 2

- name: SET AZ ZONE TO FIRST AVAILABLE
  ansible.builtin.set_fact:
    ec2_az: "{{ availability_zones[0].zone_name }}"

- name: grab information about AWS user
  amazon.aws.aws_caller_info:
    region: "{{ ec2_region }}"
  register: whoami

- name: print whoami
  ansible.builtin.debug:
    var: "whoami"

- name: save username of AWS user
  ansible.builtin.set_fact:
    aws_user: "{{ whoami.arn.split(\"/\")[-1] }}"

- name: save account id of AWS user
  ansible.builtin.set_fact:
    aws_account: "{{ whoami.account }}"
