---
- name: remove dns entries for each tower node
  when: teardown|bool
  ansible.builtin.include_tasks: teardown.yml

- name: check to see if SSL cert already applied
  register: check_cert
  failed_when: false
  when:
  - not teardown
  ansible.builtin.uri:
    url: "{{ _url_ }}"
    method: "GET"
    user: "admin"
    password: "{{ _password_ }}"
    validate_certs: true
    force_basic_auth: true

- name: create DNS entries for Automation Controller and SSL cert
  block:
    - name: create DNS entries for each Ansible control node
      ansible.builtin.include_tasks: create.yml

    - name: configure SSL cert for Automation Controller
      vars:
        dns_name: "{{ student }}.{{ ec2_name_prefix|lower }}.{{ workshop_dns_zone }}"
      include_role:
        name: "{{ playbook_dir|dirname }}/roles/issue_cert"
  when:
    - not teardown
    - check_cert.status != 200
