---
- name: retrieve zone id
  register: AWSINFO
  amazon.aws.route53_zone:
    zone: "{{ _zone_ }}"

- name: retrieve route53 info
  register: record_sets
  amazon.aws.route53_info:
    type: A
    query: record_sets
    hosted_zone_id: "{{AWSINFO.zone_id}}"
    start_record_name: "{{ _start_record_name_ }}"

- name: delete DNS entries for each student
  become: false
  vars:
    records: '{{ record_sets.ResourceRecordSets | selectattr("Name", "match", "student" + item|string + "." + ec2_name_prefix|lower + "." + workshop_dns_zone) | map(attribute="ResourceRecords")
      | list }}'
  when: records | length > 0
  amazon.aws.route53:
    state: "{{ _state_ }}"
    zone: "{{ workshop_dns_zone }}"
    record: student{{item}}.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}
    type: A
    value: "{{ range(1, student_total|int + 1)|list }}"

- name: retrieve route53 information satellite
  register: record_sets_sat
  amazon.aws.route53_info:
    type: A
    query: record_sets
    hosted_zone_id: "{{AWSINFO.zone_id}}"
    start_record_name: student1.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}

- name: delete dns entries for Satellite for each student
  become: false
  vars:
    records: '{{record_sets_sat.ResourceRecordSets | selectattr("Name", "match", "student" + item|string + "-sat." + ec2_name_prefix|lower + "." + workshop_dns_zone)
      | map(attribute="ResourceRecords") | list }}'
  when: records | length > 0
  amazon.aws.route53:
    state: "{{ s3_state }}"
    zone: "{{ workshop_dns_zone }}"
    record: student{{item}}.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}
    type: A
    value: "{{ range(1, student_total|int + 1)|list }}"

- name: GRAB ROUTE53 INFORMATION - zone subdomain root
  register: record_sets_zone_root
  amazon.aws.route53_info:
    type: A
    query: record_sets
    hosted_zone_id: "{{AWSINFO.zone_id}}"
    start_record_name: student1.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}

- name: delete dns entry for zone subdomain root
  become: false
  vars:
    records: '{{ record_sets_zone_root.ResourceRecordSets | selectattr("Name", "match", ec2_name_prefix|lower + "." + workshop_dns_zone) | map(attribute="ResourceRecords")
      | list }}'
  when: records | length > 0
  amazon.aws.route53:
    state: "{{ s3_state }}"
    zone: "{{ workshop_dns_zone }}"
    record: student{{item}}.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}
    type: A
    value: "{{ (records | first | first)['Value'] }}"
