---
- awx.awx.tower_settings:
    name: TOWER_URL_BASE
    value: https://{{ dns_name }}
    tower_verify_ssl: false
    tower_host: https://localhost/
    tower_username: admin
    tower_password: "{{ admin_password }}"
  register: change_base_url
  until: change_base_url is not failed
  retries: 12
  delay: 5
