---
- name: SSL cert block
  block:
    - name: Add EPEL repo for RHEL 9
      ansible.builtin.yum_repository:
        name: epel
        description: EPEL for Enterprise Linux 9
        baseurl: https://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/
        enabled: true
        gpgcheck: false

    - name: install snapd
      ansible.builtin.package:
        name: snapd
        state: present

    - name: start snapd
      ansible.builtin.service:
        name: snapd
        state: started

    - name: create link for snap dir
      ansible.builtin.file:
        src: /var/lib/snapd/snap
        dest: /snap
        state: link

    - name: install certbot
      ansible.builtin.command: snap install --classic certbot

    - name: add certbot in $PATH
      ansible.builtin.file:
        src: /snap/bin/certbot
        dest: /usr/bin/certbot
        state: link

    - name: install python requests
      ansible.builtin.pip:
        name: requests>=2.14.2

    - name: stop private automation hub
      register: stop_hub
      until: stop_hub is not failed
      retries: 5
      ansible.builtin.service:
        name: pulpcore-api.service
        state: stopped

    - name: stop nginx
      register: stop_nginx
      until: stop_nginx is not failed
      retries: 5
      ansible.builtin.service:
        name: nginx
        state: stopped

    - name: issue ssl cert
      register: ssl_cert
      until: ssl_cert is not failed
      retries: 5
      ansible.builtin.shell: certbot certonly --no-bootstrap --standalone -d hub-{{ student | default('student') }}.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}
        --email ansible-network@redhat.com --noninteractive --agree-tos

    - name: Move SSL Key
      ansible.builtin.copy:
        remote_src: true
        src: "{{ _src_ }}"
        dest: /etc/pulp/certs/pulp_webserver.key

    - name: move ssl cert
      ansible.builtin.copy:
        remote_src: true
        src: "{{ _src_ }}"
        dest: /etc/pulp/certs/pulp_webserver.crt

    - name: replace URL in pulp settings
      replace:
        path: /etc/pulp/settings.py
        regexp: "{{ '([0-9]{1,3}[\\.]){3}[0-9]{1,3}' }}"
        replace: hub-{{ student | default('student') }}.{{ ec2_name_prefix|lower }}.{{ workshop_dns_zone }}

  rescue:
    - name: no SSL cert for private automation hub
      debug:
        msg: SSL cert problem - no cert applied

  always:
    - name: nginx restart
      ansible.builtin.service:
        name: nginx
        state: restarted

    - name: private automation hub restart
      ansible.builtin.service:
        name: pulpcore-api.service
        state: restarted
