---
- name: Register and subscribe
  community.general.redhat_subscription:
    state: "{{ state }}"
    username: "{{ _username_ }}"
    password: "{{ _password_ }}"
    auto_attach: true
  register: task_register_var
  until: task_register_var is not failed
  retries: 5
