---
- name: load automation controller vars for specific workshop type
  with_first_found:
    - "{{role_path}}/vars/{{ workshop_type }}.yml"
    - "{{role_path}}/vars/unsupported_workshop.yml"
  ansible.builtin.include_vars: "{{ item }}"

- name: ensure controller is online and working
  register: controller_online
  until: controller_online is success
  delay: 3
  retries: 5

  # Disable collections requirements.yml and rely on only EEs
  ansible.builtin.uri:
    url: https://localhost/api/v2/ping/
    method: GET
    user: admin
    password: "{{ _password_ }}"
    validate_certs: false
    force_basic_auth: true

- name: Turn off AWX_COLLECTIONS_ENABLED on controller
  awx.awx.settings:
    name: AWX_COLLECTIONS_ENABLED
    value: "{{ _value_ }}"
    controller_username: admin
    controller_password: "{{ controller_password }}"
    controller_host: https://{{ ansible_host }}
    validate_certs: false

#### CREDENTIAL

- name: add SSH credential into Automation controller
  awx.awx.credential:
    name: Workshop Credential
    credential_type: Machine
    organization: Default
    controller_username: admin
    controller_password: "{{ admin_password }}"
    controller_host: https://{{ ansible_host }}
    validate_certs: false
    inputs:
      username: ec2-user
      ssh_key_data: "{{ lookup('file', output_dir + '/' + ec2_name_prefix + '-private.pem') }}"

- name: add controller credential into automation controller
  awx.awx.credential:
    name: Controller Credential
    credential_type: Red Hat Ansible Automation Platform
    organization: Default
    controller_username: admin
    controller_password: "{{ admin_password }}"
    controller_host: https://{{ ansible_host }}
    validate_certs: false
    inputs:
      host: "{{ student }}.{{ ec2_name_prefix }}.{{ workshop_dns_zone }}"
      username: admin
      password: "{{ admin_password }}"

- name: create workshop inventory
  awx.awx.inventory:
    name: Workshop Inventory
    organization: Default
    controller_username: admin
    controller_password: "{{ admin_password }}"
    controller_host: https://{{ ansible_host }}
    validate_certs: false
  register: workshop_inventory
  until: workshop_inventory is success
  delay: 3
  retries: 5

# - name: copy inventory to awx user
#   copy:
#     src: "/home/{{ username }}/lab_inventory/hosts"
#     remote_src: true
#     dest: "/home/{{ run_commands_user }}"
#     owner: "{{ run_commands_user }}"
#     group: "{{ run_commands_user }}"

# - name: import inventory
#   become_user: "{{ run_commands_user }}"
#   shell: 'awx-manage inventory_import --source=/home/{{ run_commands_user }}/hosts --inventory-name="Workshop Inventory"'
#   register: import_inventory
#   until: import_inventory is not failed
#   retries: 5
# #### end of inventory

### USER

- name: add student user
  awx.awx.user:
    username: "{{ _username_ }}"
    password: "{{ _password_ }}"
    email: charlotte5@example.com
    state: present
    superuser: true
    controller_username: admin
    controller_password: "{{ admin_password }}"
    controller_host: https://{{ ansible_host }}
    validate_certs: false

# Workshop specific execution environments

- name: Add specific workshop execution environment
  awx.awx.execution_environment:
    name: "{{ _name_ }}"
    image: "{{ _image_ }}"
    pull: missing
    controller_username: admin
    controller_password: "{{ admin_password }}"
    controller_host: https://{{ ansible_host }}
    validate_certs: false

- name: setup workshop specific controller information
  with_first_found:
    - "{{ role_path }}/tasks/{{ workshop_type }}.yml"
    - "{{ role_path }}/tasks/unsupported_workshop.yml"
  ansible.builtin.include_tasks: "{{item}}"
