---
- name: install apache
  ansible.builtin.package:
    name: httpd
    state: present

- name: start httpd
  ansible.builtin.service:
    name: httpd
    state: started

- name: add attack simulation files
  loop:
    - ddos_simulation
    - sql_injection_simulation
    - web_attack_simulation
  ansible.builtin.copy:
    src: "{{item}}"
    dest: /var/www/html/{{item}}
