---
- name: Install EPEL
  ansible.builtin.package:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: present

- name: setup repo
  ansible.builtin.copy:
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo

- name: selinux bindings RHEL8
  when:
    - ansible_selinux.status is defined
    - ansible_selinux.status == "enabled"
    - ansible_distribution_major_version|int == 8
  ansible.builtin.package:
    name:
      - policycoreutils-python-utils
      - python3-libselinux
    state: present

- name: Install MySQL, PHP, Git
  ansible.builtin.package:
    name:
      - mariadb-server
      - php
      - php-fpm
      - php-mysqlnd
      - php-pdo
      - python36
      - git
      - rsync
      - certbot
      - nginx
    state: present
