---
# If this fails check out status of certbot: https://letsencrypt.status.io/
- name: Issue SSL cert
  register: issue_cert
  until: issue_cert is not failed
  retries: 5
  ansible.builtin.shell: certbot certonly --no-bootstrap --standalone -d {{ ec2_name_prefix|lower }}.{{ workshop_dns_zone|lower }} --email ansible-network@redhat.com --noninteractive --agree-tos

- name: Retrieve Specific SSL cert
  register: intermediate_cert
  ansible.builtin.slurp:
    src: "{{ _src_ }}"

- name: Combine Specific and intermediate cert
  ansible.builtin.template:
    src: "combined_cert.j2"
    dest: "{{ _dest_ }}"
