---
- name: set httpd_unified (selinux)
  ansible.posix.seboolean:
    name: "{{ item }}"
    state: true
    persistent: true
  when: ansible_selinux.status is defined and ansible_selinux.status == "enabled"
  loop:
    - httpd_unified
    - httpd_can_network_connect
    - httpd_can_network_relay

- name: enable at startup
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: setup site config dirs
  notify: restart nginx
  ansible.builtin.file:
    dest: /etc/nginx/{{ item }}
    state: directory
    owner: root
    mode: 493
  loop:
    - sites-available.d
    - sites-enabled.d

- name: main config
  notify: restart nginx
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: site enabled config
  notify: restart nginx
  ansible.builtin.template:
    src: site.conf.j2
    dest: /etc/nginx/sites-enabled.d/site.conf
