---
- name: Enable TCP port 9000 for php-fpm
  notify: restart php-fpm
  ansible.builtin.lineinfile:
    path: "/etc/php-fpm.d/www.conf"
    regexp: "^listen ="
    line: "listen = 127.0.0.34:9000"

- name: Start Services
  notify: restart nginx
  ansible.builtin.service:
    name: "{{ item }}"
    state: "started"
    enabled: true
  loop:
  - mariadb
  - php-fpm

- name: Set permissions on the PHP Session directory
  ansible.builtin.file:
    path: "/var/lib/php/session/"
    owner: "nginx"
    group: "nginx"
    mode: 511
    state: "directory"

- name: Create users directory on server
  ansible.builtin.file:
    path: "/usr/share/nginx/html/"
    state: "directory"

- name: Copy users file to server
  ansible.builtin.template:
    src: "templates/index.php.j2"
    dest: "/usr/share/nginx/html/index.php"

- name: Copy files over to attendance node
  loop:
  - redhat-ansible-logo.svg
  - redhat-logo.svg
  - style.css
  - favicon.ico
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/usr/share/nginx/html/{{ item }}"

- name: Copy list file to server
  ansible.builtin.template:
    src: "templates/list.php.j2"
    dest: "/usr/share/nginx/html/list.php"

- name: Install PyMySQL
  ansible.builtin.pip:
    name: "PyMySQL"

- name: make sure any previous runs 'workshop' database is reset
  community.mysql.mysql_db:
    name: "workshop"
    state: "absent"

- name: Create a new database with name 'workshop'
  community.mysql.mysql_db:
    name: "workshop"
    state: "present"

- name: Copy SQL template to server
  register: workshopsql
  ansible.builtin.template:
    src: "templates/workshop.sql.j2"
    dest: "/tmp/workshop.sql"

- name: Import SQL file into workshop database
  community.mysql.mysql_db:
    state: "import"
    name: "workshop"
    target: "/tmp/workshop.sql"
