---
- name: Teardown attendance
  when: teardown|bool
  ansible.builtin.include_tasks: teardown.yml

- name: setup attendance instance
  block:
    - name: setup DNS specific information
      with_first_found:
        - "{{role_path}}/tasks/{{ dns_type }}.yml"
        - "{{role_path}}/tasks/none.yml"
      ansible.builtin.include_tasks: "{{ item }}"

    - name: install package dependencies for attendance instance
      ansible.builtin.include_tasks: 10_package_dependencies.yml

    - name: attempt to get SSL certificates
      block:
        - name: retrieve SSL cert with certbot
          include_tasks: 20_certbot.yml
      rescue:
        - name: append dns_information failure
          ansible.builtin.set_fact:
            dns_information:
              - "{{ dns_information }}"
              - The Lets Encrypt certbot failed for the attendance node, please check https://letsencrypt.status.io/ to make sure the service is running

        - name: error with SSL cert
          ansible.builtin.debug:
            msg: Unable to retrieve SSL cert, ERROR, continuing on without cert...

    - name: install and configure nginx on attendance node
      ansible.builtin.include_tasks: 30_nginx.yml

    - name: Configure attendance host
      import_tasks: 40_attendance.yml
  when: not teardown
