---
- name: Install EPEL
  ansible.builtin.package:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
    state: present

- name: Install base packages
  register: dnf_check
  until: dnf_check is not failed
  retries: 4
  delay: 5

  # Certbot dependancy / acme, needs later version of requests library than task above^^
  ansible.builtin.package:
    name:
      - vim
      - git
      - wget
      - nano
      - tree
      - sshpass
      - tmux
      - python3-pip
      - python3-devel
      - ansible-core
      - gcc
      - bind-utils
      - jq
      - net-tools
    state: present

- name: install awxkit and requests >2.14
  become: true
  ansible.builtin.pip:
    name:
      - awxkit
      - yamllint
      - requests==2.14.2
      - ansible-navigator
      - ansible-lint
    state: latest

- name: install community collection
  register: controlnode
  loop:
    - community.general
  until: controlnode is not failed
  retries: 5
  ansible.builtin.shell: "ansible-galaxy collection install {{ item }} --force-with-deps "
