---
- name: aap setup for control node
  tags:
    - aap_setup
  ansible.builtin.include_tasks: 10_aap_setup.yml

- name: check to see if automation controller is already up and running
  register: check_controller
  failed_when: false
  when:
    - controllerinstall is defined
    - controllerinstall|bool
  ansible.builtin.uri:
    url: https://localhost/api/v2/ping/
    method: GET
    user: admin
    password: "{{ _password_ }}"
    validate_certs: false
    force_basic_auth: true

- name: install controller if knob is set
  when:
    - controllerinstall is defined
    - controllerinstall|bool
    - check_controller.status != 200
  ansible.builtin.include_tasks: 12_controller.yml

- name: Install packages
  ansible.builtin.include_tasks: 15_package_dependencies.yml

- name: common workshop setup for control node
  ansible.builtin.include_tasks: 20_all_workshop.yml
