---
- name: grab facts for rtr1
  register: rtr1_node_facts
  delegate_to: localhost
  amazon.aws.ec2_instance_info:
    region: "{{ _region_ }}"
    filters:
      instance-state-name: running
      tag:Name: '{{ec2_name_prefix}}-{{username}}-rtr1'

- name: grab facts for rtr2
  register: rtr2_node_facts
  delegate_to: localhost
  amazon.aws.ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      tag:Name: '{{ec2_name_prefix}}-{{username}}-rtr2'

- name: grab facts for rtr3
  register: rtr3_node_facts
  delegate_to: localhost
  amazon.aws.ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      tag:Name: '{{ec2_name_prefix}}-{{username}}-rtr3'

- name: grab facts for rtr4
  register: rtr4_node_facts
  delegate_to: localhost
  amazon.aws.ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      tag:Name: '{{ec2_name_prefix}}-{{username}}-rtr4'
