---
- name: setup inventory
  ansible.builtin.include_tasks: inventory/addhost_{{workshop_type}}.yml

- name: Generate student 99-webui.json
  with_sequence: count="{{ student_total|int }}"
  ansible.builtin.template:
    src: "{{ _src_ }}"
    dest: "{{ playbook_dir }}/{{ec2_name_prefix}}/student{{item}}-99-webui.json"
