---
- name: overwrite select ec2_info vars if ec2_xtra vars are provided
  when: (ec2_xtra is defined) and (ec2_xtra is not none)
  ansible.builtin.set_fact:
    ec2_info: "{{ ec2_info|combine(ec2_xtra) }}"

- when: teardown|bool
  ansible.builtin.include_tasks: teardown.yml

- name: provision aws resources and instances
  tags: provisioned
  when: not teardown|bool
  ansible.builtin.include_tasks: provision.yml
