---
- name: ensure workshop folder {{ ec2_name_prefix }} exists
  ansible.builtin.file:
    path: "{{ playbook_dir }}/{{ ec2_name_prefix }}"
    state: "directory"

## These AWS resources are used for every workshop type
## This includes VPC, subnet, Security Group, Internet Gateway and route table

- name: provision aws resources
  ansible.builtin.include_tasks: resources/resources.yml

- name: provision networking aws resources
  when: workshop_type == 'network' or workshop_type == 'demo'
  ansible.builtin.include_tasks: resources/resources_{{workshop_type}}.yml

- name: find ami if no ami provided
  when: not pre_build|bool
  block:
    - name: find ami for ansible control node
      amazon.aws.ec2_ami_info:
        region: "{{ ec2_region }}"
        owners: "{{ _owners_ }}"
        filters:
          name: '{{ ec2_info[control_type].filter }}'
          architecture: '{{ ec2_info[control_type].architecture }}'
      register: amis

    - name: save ami for ansible control node
      ansible.builtin.set_fact:
        ansible_control_node_ami: "{{ amis.images | selectattr('name', 'defined') | sort(attribute='name') | last }}\n"

- name: save ami for ansible control node pre_build
  when: pre_build|bool
  block:
    - name: find ami for ansible control node with pre_build image
      amazon.aws.ec2_ami_info:
        region: "{{ ec2_region }}"
        owners: "{{ ec2_info[control_type].owners }}"
        filters:
          name: '{{ ec2_info.control_type_pre_build.filter }}'
          architecture: '{{ ec2_info.control_type_pre_build.architecture }}'
      register: amis

    - name: save ami for ansible control node
      ansible.builtin.set_fact:
        ansible_control_node_ami: "{{ amis.images | selectattr('name', 'defined') | sort(attribute='name') | last }}  \n"

    - name: check if we have access to pre_build AMI images
      ansible.builtin.include_tasks: check_prebuild.yml

- name: enforce major and minor version are at least RHEL 8.4
  when:
  - not pre_build|bool
  - control_type == "rhel8-tower"
  ansible.builtin.assert:
    that:
    - ansible_control_node_ami.name[7]|int >= 4
    - ansible_control_node_ami.name[5]|int >= 8
    msg: "AWS ec2 image retrieved will not work with AAP 2, we need at least RHEL 8.4"

- name: enforce major and minor version are at least RHEL 9.2
  when:
  - not pre_build|bool
  - control_type == "rhel9-controller"
  ansible.builtin.assert:
    that:
    - ansible_control_node_ami.name[7]|int >= 2
    - ansible_control_node_ami.name[5]|int >= 9
    msg: "AWS ec2 image retrieved will not work with AAP 2, we need at least RHEL 9.2"

- name: Create the control clusters
  loop: "{{ range(1, control_nodes|default(1) + 1 ) | list }}"
  loop_control:
    loop_var: sequence
  ansible.builtin.include_tasks: cluster_instances.yml

- name: configure attendance host
  when: attendance|bool

## create private automation hub
  ansible.builtin.include_tasks: 'attendance.yml'

- name: configure automation hub host
  when: automation_hub|bool

## find AMI - amazon machine images dynamically
  ansible.builtin.include_tasks: 'automation_hub.yml'

- name: find correct AMI
  ansible.builtin.include_tasks: 'ami_find/ami_find_{{ workshop_type }}.yml'

- name: check if we have access to pre_build hub AMI images
  when: automation_hub|bool and pre_build|bool

## Instance creation
  ansible.builtin.include_tasks: check_prebuild_hub.yml

- name: provision workshop instances
  ansible.builtin.include_tasks: 'instances/instances_{{ workshop_type }}.yml'

- name: create instructor_inventory, and student files
  ansible.builtin.include_tasks: create_inventory.yml

- name: create cockpit/machines.d webui definition file
  when: workshop_type == "ripu"
  ansible.builtin.include_tasks: cockpit_machines.yml
